StudyPlace/Web/Areas/Dashboard/Controllers/PanelController.cs
using AutoMapper;
using Domain.Models;
using Domain.Repository;
using Microsoft.AspNet.Identity;
using Services.Helpers;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Web.Areas.Dashboard.Models;
using Web.Filters;
using Web.Models;

namespace Web.Areas.Dashboard.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
        private IBaseRepository<Aluno> companyRepository;
        private IBaseRepository<Professor> workerRepository;
        private IBaseRepository<Address> addressRepository;
        private IBaseRepository<Specialty> specialityRepository;      
        private IBaseRepository<Course> courseRepository;

        public PanelController(IBaseRepository<Aluno> _companyRepository, IBaseRepository<Professor> _workerRepository,
            IBaseRepository<Address> _addressRepository, IBaseRepository<Specialty> _specialityRepository,
            IBaseRepository<Course> _courseRepository)
        {
            companyRepository = _companyRepository;
            workerRepository = _workerRepository;
            addressRepository = _addressRepository;
            specialityRepository = _specialityRepository;
            courseRepository = _courseRepository;
        }

        //[ClaimsAuthorize("Role", "aluno")]
        public ActionResult IndexCompany()
        {
            var id = User.Identity.GetUserId();
            var company = companyRepository.List
                .FirstOrDefault(x => x.Id == id);

            //int workerCount = workerRepository.List
            //    .ToList().Count();

            var model = Mapper.Map<Aluno, AlunoViewModel>(company);

            if (company != null)
            {
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }

        //[ClaimsAuthorize("Role", "worker")]
        public ActionResult IndexWorker()
        {
            string idUser = User.Identity.GetUserId();

            var worker = workerRepository.List.FirstOrDefault(x => x.Id == idUser);

            var model = Mapper.Map<Professor, ProfessorViewModel>(worker);
            //@ViewBag.ImageUrl = worker.ImageUrl;

            return View(model);
        }

        [ClaimsAuthorize("Role", "worker")]
        public ActionResult EditCurriculum(string curriculumId)
        {
            if (curriculumId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string idUser = User.Identity.GetUserId();

            var worker = workerRepository.List.FirstOrDefault(x => x.Id == idUser);

            var model = Mapper.Map<Professor, EditWorkerViewModel>(worker);

            model.LanguageIds = (from n in model.Languages.ToList() select n.Id.ToString()).ToList();

            return View(model);
        }

        [HttpPost]
        [ClaimsAuthorize("Role", "worker")]
        public ActionResult EditCurriculum(EditWorkerViewModel model, HttpPostedFileBase profileImage)
        {
            if (ModelState.IsValid)
            {
                string idUser = User.Identity.GetUserId();

                var worker = workerRepository.List.FirstOrDefault(x => x.Id == idUser);

                var address = addressRepository.List.FirstOrDefault(x => x.Id == model.Address.Id);
                address.Street = model.Address.Street;
                address.City = model.Address.City;
                address.State = model.Address.State;

                addressRepository.Update(address);

                worker.FullName = model.FullName;
                worker.PhoneNumber = model.PhoneNumber;

                if (profileImage != null)
                {
                    var imageName = Guid.NewGuid().ToString() + "." + profileImage.FileName.Split('.').Last();
                    worker.ImageUrl = AzureFileHelper.SaveFile(imageName, profileImage.InputStream);
                }
                
                workerRepository.Update(worker);

                return RedirectToAction("IndexWorker");
            }
            
            return View(model);
        }

        public ActionResult ModalGraduate()
        {
            var courses = courseRepository.List.OrderBy(x => x.Description);
            ViewBag.Courses = new SelectList(courses, "Description", "Description");

            var titles = new List<SelectListItem> {
                new SelectListItem { Text = "Técnico", Value = "Técnico" },
                new SelectListItem { Text = "Graduação", Value = "Graduação" },
                new SelectListItem { Text = "Especialização", Value = "Especialização" },
                new SelectListItem { Text = "Mestrado", Value = "Mestrado" } ,
                new SelectListItem { Text = "Doutorado", Value = "Doutorado" }
            };

            ViewBag.Titles = new SelectList(titles, "Value", "Text");

            return PartialView("Partials/_EditGraduate");
        }

        public ActionResult ModalServiceHistory()
        {
            return PartialView("Partials/_EditServiceHistory");
        }
    }
}

StudyPlace/Web/Areas/Dashboard/Views/Panel/Partials/_Details.cshtml
@model Web.Models.OpportunityViewModel

<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fechar</span></button>
			<h4 class="modal-title">Detalhes da Oportunidade</h4>
		</div>
		<div class="modal-body">
			<table cellspacing="10" cellpadding="10" class="">
				<tr>
					<td width="50%"><label>@Html.DisplayNameFor(model => model.ActivityAreaId)</label></td>
					<td>
						<label>@Model.ActivityArea.Description</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.SpecialtyId)</label></td>
					<td>
						<label>@Model.Specialty.Description</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.TypeOfContract)</label></td>
					<td>
						<label>@Model.TypeOfContract</label>
					</td>
				</tr>


				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Attachments)</label></td>
					<td>
						<a href="https://studyplace.blob.core.windows.net/uploads/@Html.DisplayFor(model => model.Attachments)">
							Download
						</a>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.OrganBidder)</label></td>
					<td>
						<label>@Model.OrganBidder</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.TypeOfContract)</label></td>
					<td>
						<label>@Model.TypeOfContract</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Local)</label></td>
					<td>
						<label>@Model.Local</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Value)</label></td>
					<td>
						<label>@Model.Value</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.PartnerType)</label></td>
					<td>
						<label>@Model.PartnerType</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.ExperienceRequired)</label></td>
					<td>
						<label>@Model.ExperienceRequired</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Percentual)</label></td>
					<td>
						<label>@Model.Percentual</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Company.FullName)</label></td>
					<td>
						<label>@Model.Company.FullName</label>
					</td>
				</tr>

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Company.Email)</label></td>
					<td>
						<label>@Model.Company.Email</label>
					</td>
				</tr>

				@if (Model.Company.Addresses.Count() != 0)
				{
						<tr>
							<td><label>@Html.DisplayNameFor(model => model.Company.Addresses.FirstOrDefault().Street)</label></td>
							<td>
								<label>@Model.Company.Addresses.FirstOrDefault().Street</label>
							</td>
						</tr>
				}

				<tr>
					<td><label>@Html.DisplayNameFor(model => model.Company.PhoneNumber)</label></td>
					<td>
						<label>@Model.Company.PhoneNumber</label>
					</td>
				</tr>
			</table>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
		</div>
	</div>
</div>

StudyPlace/Web/Areas/Dashboard/Views/Panel/Partials/_EditGraduate.cshtml
@model Web.Models.GraduatedInViewModel

<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fechar</span></button>
			<h4 class="modal-title">Formação</h4>
		</div>
		<div class="modal-body">
			@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
            {
					@Html.AntiForgeryToken()

					<div class="form-slider">
						<div class="form-group col-xs-12">
							<div class="form-material form-material-primary">
								@Html.LabelFor(model => model.EducationalInstitution)
								@Html.TextBoxFor(model => model.EducationalInstitution, new { @class = "form-control", @placeholder = "Instituição de Ensino", @id = "txtEducationalInstitution" })
								@Html.ValidationMessageFor(m => m.Course, null, new { @class = "text-danger", @id = "errEducationInstitution" })
							</div>
						</div>

						<div class="form-group col-xs-12">
							<div class="form-material form-material-primary">
								@Html.LabelFor(model => model.Title)
								@Html.DropDownListFor(model => model.Title, ViewBag.Titles as SelectList, "Selecione", new { @class = "form-control selectpicker push-10-t", @title = "Selecione", @id = "dropDownTitle", @onchange= "hideOtherCourseField(this)" })
								@Html.ValidationMessageFor(m => m.Title, null, new { @class = "text-danger", @id = "errTitle" })
							</div>
						</div>

						<div class="form-group col-xs-12">
							<div class="form-material form-material-primary">
								@Html.LabelFor(model => model.Course)
								<div id="courseArea">
									@Html.DropDownListFor(model => model.Course, ViewBag.Courses as SelectList, "Selecione", new { @class = "form-control selectpicker", @placeholder = "Curso", @id = "txtCourse" })
								</div>
								
								@Html.TextBoxFor(model => model.OtherCourse, new { @class = "form-control", @placeholder = "Curso", @id = "txtOtherCourse" })
								@Html.ValidationMessageFor(m => m.Course, null, new { @class = "text-danger", @id = "errCourse" })
							</div>
						</div>

						<div class="form-group">							
								<div class="col-xs-12">
									<div class="form-material form-material-primary">
										@Html.LabelFor(model => model.ConclusionYear)
										@Html.TextBoxFor(model => model.ConclusionYear, new { @class = "form-control", @style="width: 200px !important;", @placeholder = "Ano de Conclusão", @id = "txtYearConclusion" })
										@Html.ValidationMessageFor(m => m.ConclusionYear, null, new { @class = "text-danger", @id = "errYearConclusion" })
									</div>								
								
							</div>
						</div>
					</div>
			}
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			<button type="button" id="modalProfessionalExperience" onclick="if (validationGraduated()) { addRowTableGraduated() };" class="btn btn-primary">Adicionar</button>
		</div>
	</div>
</div>

StudyPlace/Web/Areas/Dashboard/Views/Panel/Partials/_EditProfessionalExperience.cshtml
@model Web.Models.ProfessionalExperienceViewModel
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fechar</span></button>
			<h4 class="modal-title">Experiência Profissional</h4>
		</div>
		<div class="modal-body">
			@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
            {
					@Html.AntiForgeryToken()
					<div class="form-slider">
						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									@Html.LabelFor(model => model.ActivityAreaDescription)
									@Html.DropDownListFor(model => model.ActivityAreaDescription, ViewBag.ActivityAreas as SelectList, "Selecione", new { @class = "form-control push-10-t selectpicker", @title = "Selecione", @id = "txtActivity" })
									@Html.ValidationMessageFor(m => m.ActivityAreaDescription, null, new { @class = "text-danger", @id = "errActivity" })
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									@Html.LabelFor(model => model.ProjectName)
									@Html.TextBoxFor(model => model.ProjectName, new { @class = "form-control", @placeholder = "Nome do Projeto", @id = "txtProjectName" })
									@Html.ValidationMessageFor(m => m.ProjectName, null, new { @class = "text-danger", @id = "errProjectName" })
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									@Html.LabelFor(model => model.Client)
									@Html.TextBoxFor(model => model.Client, new { @class = "form-control", @placeholder = "Cargo / Função", @id = "txtOffice" })
									@Html.ValidationMessageFor(m => m.Client, null, new { @class = "text-danger", @id = "errOffice" })
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									<label for="frontend-contact-msg">Especialidade:</label>
									@Html.DropDownListFor(model => model.ProfessionalSpecialtyId, ViewBag.ProfessionalSpecialties as SelectList, new Dictionary<string, object>() { { "class", "form-control selectpicker search" }, { "title", "Selecione" }, { "id", "txtSpecialtyProfessional" } })
									@Html.ValidationMessageFor(model => model.ProfessionalSpecialtyId, null, new { @class = "text-danger" })
								</div>
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									@Html.Label("Período: *", new { @class = "push-07-t" })
									<div class="row">
										<div class="col-md-5">
											@Html.TextBoxFor(model => model.StartExecutionPeriod, new { @class = "form-control  modalProfessionalExperienceExecutionPeriod datepicker", @type = "text", @id = "txtStartPeriod", @readonly = "true" })
											@Html.ValidationMessageFor(m => m.StartExecutionPeriod, null, new { @class = "text-danger", @id = "errStartPeriod" })
										</div>
										<div class="col-xs-1">
											<br />
											@Html.Label("Até:", new { @class = "push-04-t" })
										</div>
										<div class="col-md-5">
											@Html.TextBoxFor(model => model.EndExecutionPeriod, new { @class = "form-control  modalProfessionalExperienceExecutionPeriod datepicker", @type = "text", @id = "txtEndPeriod", @readonly = "true" })
											@Html.ValidationMessageFor(m => m.EndExecutionPeriod, null, new { @class = "text-danger", @id = "errEndPeriod" })
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-12">
								@Html.LabelFor(model => model.PerformedActivities)
								@Html.TextAreaFor(model => model.PerformedActivities, new { @class = "form-control", @placeholder = "Atividades Desempenhadas", @id = "txtPerformedActivities", @rows = 5 })
								@Html.ValidationMessageFor(m => m.PerformedActivities, null, new { @class = "text-danger", @id = "errPerformedActivities" })
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									<label>Acervo Técnico: *</label>
									<div class="row">
										<div class="col-sm-2">
											<input type="radio" class="radio radio-inline" name="acervo_tecnico" value="sim" checked="checked" /> Sim
										</div>
										<div class="col-sm-2">
											<input type="radio" class="radio radio-inline" name="acervo_tecnico" value="nao" /> Não
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
            }
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			<button type="button" id="modalProfessionalExperience" onclick="if (validationProfessionalExperience()) { addRowProfessionalExperiences(); }" class="btn btn-primary">Adicionar</button>
		</div>
	</div>
</div>

StudyPlace/Web/Areas/Dashboard/Views/Panel/Partials/_EditServiceHistory.cshtml
@model Web.Models.HistoricalOfServiceViewModel
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Fechar</span></button>
			<h4 class="modal-title">Histórico de Serviços</h4>
		</div>
		<div class="modal-body">
			@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { @class = "form-horizontal" }))
            {
					@Html.AntiForgeryToken()
					<div class="form-slider">
						<div class="form-group">
							<div class="col-xs-12">
								<div class="form-material form-material-primary">
									@Html.LabelFor(model => model.Company)
									@Html.TextBoxFor(model => model.Company, new { @class = "form-control", @placeholder = "Empresa", @id = "txtCompany" })
									@Html.ValidationMessageFor(m => m.Company, null, new { @class = "text-danger", @id = "errCompany" })
								</div>
							</div>
						</div>
					</div>
								<div class="form-group">
									<div class="col-xs-12">
										<div class="form-material form-material-primary">
											@Html.LabelFor(model => model.Office)
											@Html.TextBoxFor(model => model.Office, new { @class = "form-control", @placeholder = "Cargo / Função", @id = "txtOffice" })
											@Html.ValidationMessageFor(m => m.Office, null, new { @class = "text-danger", @id = "errOffice" })
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="col-xs-12">
										<div class="form-material form-material-primary">
											@Html.Label("Período: *", new { @class = "push-07-t" })
											<div class="row">
												<div class="col-md-5">
													@Html.TextBoxFor(model => model.PeriodStartDate, new { @class = "form-control modalHistoricalOfServicePeriodDate  datepicker", @placeholder = "", @type = "text", @id = "txtStartPeriod" })
													@Html.ValidationMessageFor(m => m.PeriodStartDate, null, new { @class = "text-danger", @id = "errStartPeriod" })
												</div>
												<div class="col-xs-1">
													@Html.Label("Até:", new { @class = "push-07-t", @style = "margin-top: 25px;" })
												</div>
												<div class="col-md-5">
													@Html.TextBoxFor(model => model.PeriodEndDate, new { @class = "form-control modalHistoricalOfServicePeriodDate datepicker", @placeholder = "", @type = "text", @id = "txtEndPeriod" })
													@Html.ValidationMessageFor(m => m.PeriodEndDate, null, new { @class = "text-danger", @id = "errEndPeriod" })
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="col-xs-12">
											@Html.LabelFor(model => model.SummaryOfActivities)
											@Html.TextAreaFor(model => model.SummaryOfActivities, new { @class = "form-control", @placeholder = "Atividades Desempenhadas", @id = "txtSummaryOfActivities", @rows = 5 })
											@Html.ValidationMessageFor(m => m.SummaryOfActivities, null, new { @class = "text-danger", @id = "errSummaryOfActivies" })
									</div>
								</div>
            }
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
			<button type="button" id="modalHistoricalOfServices" onclick="if (validationHistoricalOfServices()) { addRowHistoricalOfServices(); }" class="btn btn-primary">Adicionar</button>
		</div>
	</div>
</div>

StudyPlace/Web/Areas/Dashboard/Views/Panel/Partials/_GridBuyCompany.cshtml
@model Web.Areas.Dashboard.Models.CompanySearchViewModel
<div class="block">
	<div class="row">
		@using (Html.BeginForm("SearchCompany", "Panel", FormMethod.Post, new { id = "searchCompany", @class = "form-horizontal" }))
		{
				<div class="row">
					<div class="col-lg-12">
						<div class="form-group-sm col-sm-6">
							<div class="form-material form-material-success" style="margin-top: 20px !important;">
								<label>Área de Atividade</label>
								@Html.DropDownListFor(model => model.HiveOfActivityId, ViewBag.HiveOfActivity as SelectList, "Selecione", new { @class = "form-control selectpicker input-sm", onchange = @"form.submit();" })
							</div>
						</div>

						<div class="form-group-sm col-sm-6">
							<div class="form-material form-material-success" style="margin-top: 20px !important;">
								<label>Especialidade</label>
								@Html.DropDownListFor(model => model.SpecialtyId, ViewBag.SpecialtyCompany as SelectList, "Selecione", new { @class = "form-control selectpicker input-sm", onchange = @"form.submit();" })
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12">
						<div class="form-group-sm col-sm-6">
							<div class="form-material form-material-success">
								<label>Localidade</label>
								@Html.TextBoxFor(model => model.Localization, new { @placeholder = "Palavra Chave", @class = "form-control input-sm", onblur = @"validateEmptyFields(this, searchCompany);" })
							</div>
						</div>

						<div class="form-group-sm col-sm-6">
							<div class="form-material form-material-success">
								<label>Experiência</label>
								@Html.TextBoxFor(model => model.WordExperienceKeyCompany, new { @placeholder = "Palavra Chave", @class = "form-control input-sm", onblur = @"validateEmptyFields(this, searchCompany);" })
							</div>
						</div>
					</div>
				</div>
		}
	</div>
</div>

<table class="table table-bordered table-striped js-dataTable-full">
	<thead>
		<tr>
			<th>Data</th>
			<th>Área de Atividade</th>
			<th>Especialidade</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@if (Model != null)
		{
			foreach (var item in Model.Companies)
			{
						<tr>
							<td>@item.CreatedDateTime.ToShortDateString()</td>

							@if (item.HiveOfActivities.Count != 0)
							{
								if (item.HiveOfActivities.Count > 1)
								{
											<td>@item.HiveOfActivities.FirstOrDefault().Description + ...</td>
								}
								else
								{
											<td>@item.HiveOfActivities.FirstOrDefault().Description</td>
								}
							}
							@if (item.Specialties.Count != 0)
							{
								if (item.Specialties.Count > 1)
								{
											<td>@item.Specialties.FirstOrDefault().Description + ...</td>
								}
								else
								{
											<td>@item.Specialties.FirstOrDefault().Description</td>
								}
							}

							<td width="15%" style="text-align:center;">
								<div class="btn-group">
									<a class="btn btn-xs btn-default modalLeadDetailsCompany" data-id="@item.Id" data-toggle="tooltip" title="" data-original-title="Ver detalhes do lead"><i class="si si-magnifier"></i></a>
									@*<a class="btn btn-xs btn-success modalLeadPrePurchaseCompany" data-id="@item.Id" data-toggle="tooltip" title="" data-original-title="Abrir contato">Comprar Lead</a>*@
								</div>
							</td>
						</tr>
			}
		}
	</tbody>
</table>

StudyPlace/Web/Areas/Dashboard/Views/Panel/Partials/_GridBuyWorker.cshtml
@model Web.Areas.Dashboard.Models.WorkerSearchViewModel

<div class="row block">
    <div class="row">
        @using (Html.BeginForm("SearchWorker", "Panel", FormMethod.Post, new { @id = "searchWorker", @class = "form -horizontal" }))
				{
            <div class="col-md-12 pull-left">
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Residência</label>
                        @Html.TextBoxFor(model => model.Residence, new { @placeholder = "Palavra Chave", @class = "form-control input-sm push-10-t", onblur = @"validateEmptyFields(this, searchWorker);" })
                    </div>
                </div>
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Formação</label>
                        @Html.DropDownListFor(model => model.Course, ViewBag.GraduatedIn as SelectList, "Selecione", new { @class = "form-control input-sm push-10-t", onchange = @"form.submit();" })
                    </div>
                </div>
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Tempo de Formação</label>
                        @Html.TextBoxFor(model => model.TrainingTime, new { @placeholder = "Tempo de Formação", @type = "number", @class = "form-control input-sm push-10-t", onblur = @"validateEmptyFields(this, searchWorker);" })
                    </div>
                </div>
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Titulação</label>
                        @Html.DropDownListFor(model => model.Title, new List<SelectListItem> {
                                                                                                new SelectListItem { Text = "Graduação", Value = "Graduação" },
                                                                                                new SelectListItem { Text = "Especialização", Value = "Especialização" },
                                                                                                new SelectListItem { Text = "Mestrado", Value = "Mestrado" } ,
                                                                                                new SelectListItem { Text = "Doutorado", Value = "Doutorado" }
                                                        }, "Selecione", new { @class = "form-control push-10-t", @title = "Selecione", onchange = @"form.submit();" })
                    </div>
                </div>
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Área de Atividade</label>
                        @Html.DropDownListFor(model => model.ActivityAreaId, ViewBag.ActivityArea as SelectList, "Selecione", new { @class = "form-control input-sm push-10-t", onchange = @"form.submit();" })
                    </div>
                </div>
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Acervo Técnico</label>
                        @Html.DropDownListFor(model => model.TechnicalAssets,
                                            new List<SelectListItem> { new SelectListItem { Text = "Sim", Value = "true" },
                                            new SelectListItem { Text = "Não", Value = "false" } }, "Selecione",
                                    new { @class = "form-control input-sm push-10-t", @id = "acervoTecnico", onchange = @"form.submit();" })
                    </div>
                </div>
            </div>
            <div class="col-md-12 pull-left">
                <div class="form-group-sm col-sm-2">
                    <div class="form-material form-material-success">
                        <label>Endereço</label>
                        @Html.TextBoxFor(model => model.WordExperienceKeyWorker, new { @class = "form-control input-sm push-10-t", @placeholder = "Palavra Chave", onblur = @"validateEmptyFields(this, searchWorker);" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<table class="table table-bordered table-striped js-dataTable-full">
	<thead>
		<tr>
			<th>Residência</th>
			<th>Formação Acadêmica</th>
			<th>Ano de Conclusão</th>
			<th>Titulação</th>
			<th>Área de Atividade</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@if (Model != null)
		{
			foreach (var item in Model.Workers)
			{
						<tr>
							<td>@item.Address.Street - @item.Address.City, @item.Address.State </td>
							@if (item.GraduatedIn.Count > 1)
							{
									<td>@item.GraduatedIn.FirstOrDefault().Course + ...</td>
							}
							else
							{
									<td>@item.GraduatedIn.FirstOrDefault().Course</td>
							}

							<td>@item.GraduatedIn.FirstOrDefault().ConclusionYear</td>
							<td>@item.GraduatedIn.FirstOrDefault().Title</td>
							<td>@item.ProfessionalExperiences.FirstOrDefault().ActivityArea.Description</td>

							<td width="15%" style="text-align:center;">
								<div class="btn-group">
									<a class="btn btn-xs btn-default modalLeadDetailsWorker" data-id="@item.Id" data-toggle="tooltip" title="" data-original-title="Ver detalhes do lead"><i class="si si-magnifier"></i></a>
									@*<a class="btn btn-xs btn-success modalLeadPrePurchaseWorker" data-id="@item.Id" data-toggle="tooltip" title="" data-original-title="Abrir contato">Comprar Lead</a>*@
								</div>
							</td>
						</tr>
			}
		}
	</tbody>
</table>