StudyPlace/Web/Models/ForumViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Web.Areas.Dashboard.Models;
using Web.Models.Enuns;

namespace Web.Models
{
    public class ForumViewModel
    {
        public ForumViewModel()
        {
            this.CreateDate = DateTime.UtcNow;
        }
        
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Nome do Forum é um campo obrigatório")]
        [Display(Name = "Nome do Forum")]
        public string NomeForum { get; set; }
        
        [Required(ErrorMessage = "Curso Referência é um campo obrigatório")]
        [Display(Name = "Curso Referência")]
        public string Curso { get; set; }

        public AlunoViewModel AlunoCriador { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime CreateDate { get; set; }
    }
}

StudyPlace/Web/Areas/Dashboard/Controllers/ForumController.cs
using AutoMapper;
using Domain.Models;
using Domain.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Areas.Dashboard.Controllers
{
    public class ForumController : Controller
    {
        private IBaseRepository<Aluno> alunoRepository;
        private IBaseRepository<Forum> forumRepository;
        private IBaseRepository<Mensagens> mensagemRepository;

        public ForumController(IBaseRepository<Aluno> _alunoRepository, IBaseRepository<Forum> _forumRepository,
            IBaseRepository<Mensagens> _mensagemRepository)
        {
            alunoRepository = _alunoRepository;
            forumRepository = _forumRepository;
            mensagemRepository = _mensagemRepository;
        }

        // GET: Dashboard/Aluno
        public ActionResult Index()
        {
            var foruns = forumRepository.List;
            
            var model = Mapper.Map<IQueryable<Forum>, List<ForumViewModel>>(foruns);

            return View(model);
        }

        // GET: Dashboard/Aluno/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Dashboard/Aluno/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Aluno/Create
        [HttpPost]
        public ActionResult Create(ForumViewModel model)
        {
            try
            {
                var userName = User.Identity.Name;

                var forum = Mapper.Map<ForumViewModel, Forum>(model);

                var aluno = alunoRepository.List.FirstOrDefault(x => x.UserName == userName);

                forum.AlunoCriador = aluno;
                
                forumRepository.Insert(forum);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Aluno/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dashboard/Aluno/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Aluno/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dashboard/Aluno/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StudyPlace/Web/Areas/Dashboard/Views/Forum/Create.cshtml
@model Web.Models.ForumViewModel

@{
    ViewBag.Title = "Criar Fórum";

}
<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7"><h1 class="page-heading">Criar Fórum</h1></div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="@Url.Action("Index", "Home")">Home</a></li>
                <li>Criar Fórum</li>
            </ol>
        </div>
    </div>
</div>
<div class="content">
    <div class="block">
        <div class="block-content">
            <div>
                <div class="">
                    <div class="push-30-t push-20 animated fadeIn">
                        @using (Html.BeginForm("Create", "Forum", FormMethod.Post, new { @class = "form-horizontal" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <div class="text-center">
                                    <h4>Criar Novo Fórum</h4>
                                </div>
                                <hr />

                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <div class="form-material form-material-success">
                                            @Html.TextBoxFor(model => model.NomeForum, new { @class = "form-control", @placeholder = "Nome do Fórum", @id = "textFullName" })
                                            @Html.LabelFor(model => model.NomeForum)
                                            @Html.ValidationMessageFor(m => m.NomeForum, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-xs-12">
                                        <div class="form-material form-material-success">
                                            @Html.TextBoxFor(model => model.Curso, new { @class = "form-control", @placeholder = "Curso de Referência", @id = "textFullName" })
                                            @Html.LabelFor(model => model.Curso)
                                            @Html.ValidationMessageFor(m => m.Curso, null, new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudyPlace/Web/Areas/Dashboard/Views/Forum/Index.cshtml
@model IEnumerable<Web.Models.ForumViewModel>
@{
    ViewBag.Title = "Todos os Foruns";

}
<div class="content bg-gray-lighter">
    <div class="row items-push">
        <div class="col-sm-7"><h1 class="page-heading">Todos os Foruns</h1></div>
        <div class="col-sm-5 text-right hidden-xs">
            <ol class="breadcrumb push-10-t">
                <li><a class="link-effect" href="@Url.Action("Index", "Home")">Home</a></li>
                <li>Todos os Foruns</li>
            </ol>
        </div>
    </div>
</div>
<div class="content">
    <div class="block">
        <div class="block-content">
            <p>
                <a class="btn btn-lg btn-success" href="@Url.Action("Create", "Forum")" data-original-title="Criar Novo Fórum">Criar Novo Fórum</a>
            </p>
            <table class="table table-bordered table-striped js-dataTable-full">
                <thead>
                    <tr>
                        <th>Data da Criação</th>
                        <th>Nome do Fórum</th>
                        <th>Curso de Referência</th>
                        <th>Criador</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.CreateDate)</td>
                                <td>@Html.DisplayFor(modelItem => item.NomeForum)</td>
                                <td>@Html.DisplayFor(modelItem => item.Curso)</td>
                                <td>@Html.DisplayFor(modelItem => item.AlunoCriador.FullName)</td>
                                <td>
                                    <a class="btn btn-xs btn-success modalOpportunityPrePurchase" href="@Url.Action("Index", "Mensagens", new { id = item.Id })" data-toggle="tooltip" title="" data-original-title="Mensagens">Mensagens</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>